cc_library(
    name = "server",
    hdrs = ["server.h"],
    srcs = ["server.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//external:glog",
        "//third_party/http_server:http_server",
    ],
)